
name: Reproduce paper

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      PAPER_DIR: ./paper
      PAPER_FILE: paper

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up TeX environment
        run: sudo apt-get update && sudo apt-get install texlive texlive-luatex texlive-publishers texlive-science texlive-fonts-extra texlive-bibtex-extra cm-super dvipng

#      - name: Generate matrices
#        run: python reproduce/generate_matrices.py

      - name: Generate plots and tables
        run: python reproduce/generate_results.py

      - name: Obtain commit hash and time
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "build_time=$(date +'%Y-%m-%d at %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Generate paper
        run: |
          echo "The code for our numerical experiments can be found on \url{${{ github.server_url }}/${{ github.repository }}}. The figures and tables were generated from the commit \href{${{ github.server_url }}/${{ github.repository }}/tree/${{ env.sha_short }}}{${{ env.sha_short }}} on ${{ env.build_time }}." > "${{ env.PAPER_DIR }}/re-pro-badge.tex"
          python reproduce/generate_paper.py

      - name: Upload paper as PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: outcomes
          path: |
            ${{ env.PAPER_DIR }}/${{ env.PAPER_FILE }}.pdf

      - name: Upload generated files to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add paper/plots/*.pgf paper/tables/*.tex paper/re-pro-badge.tex
          git commit -m "automatically reproduce paper"
          git push
